[package]
name = "kliprs-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
chrono = "0.4.37"
clipboard = "0.5.0"
kliprs-core = { version = "0.1.0", path = "../kliprs-core" }
r2d2 = "0.8.10"
r2d2_sqlite = "0.24.0"
rusqlite = "0.31.0"
tokio = "1.37.0"
