[package]
name = "kliprs-core"
version = "0.1.0"
edition = "2021"

[dependencies]
kliprs-utils = { version = "0.1.0", path = "../kliprs-utils" }
lazy_static = "1.4.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
tempfile = "3.10.1"
